Update import and notification methods in ollama_lsp
Using this plugin with pygls v2 was throwing the following errors:

`from pygls.server import LanguageServer
ImportError: cannot import name 'LanguageServer' from 'pygls.server'
`
and "send_notification" method not found.

This method was removed in the newest version without deprecation warning.

Since there is no fixed requirement of pygls version I updated the import and method according to the [documentation](https://pygls.readthedocs.io/en/latest/pygls/howto/migrate-to-v2.html)